import { Story } from "inkjs";

export const centerGameObjects = (objects) => {
  objects.forEach(function (object) {
    object.anchor.setTo(0.5);
  });
};

export const loadStory = () => {
  //Load .json file generated by inklecate
  //And create story object
  const json = game.cache.getJSON("story");
  const story = new Story(json);
  return story;
};
