import inkjs from 'inkjs'

export const centerGameObjects = (objects) => {
  objects.forEach(function (object) {
    object.anchor.setTo(0.5)
  })
}

export const loadStory = (json) => {
  //Load .json file generated by inklecate
  //And create story object
  var json = game.cache.getJSON('story');
  let story = new inkjs.Story(json);
  return story;

}
